[project]
name = "rykit"
description = "Various helpful tools for doing systems work"
readme = "README.md"
authors = [ 
    { name = "Ryan Kosta", email = "rkosta@ucsd.edu" }
]
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = ["pandas"]
# 1. Tell the project the version is dynamic
dynamic = ["version"]


[build-system]
# 2. Switch to hatchling and include the hatch-vcs plugin
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
lint = [
    "mypy>=1.14.1",
    "pandas-stubs>=2.0.3.230814",
    "ruff>=0.15.8",
    "types-requests>=2.32.0.20241016",
]

[tool.hatch.version]
# 3. Enable VCS (Git) versioning
source = "vcs"

[tool.hatch.build.targets.wheel]
packages = ["src/rykit"]

[tool.ruff]
# Target version for syntax
target-version = "py312"
line-length = 88

[tool.ruff.lint]
# E: pycodestyle, F: Pyflakes, I: isort, D: pydocstyle (docstrings)
select = ["E", "F", "I", "D"]
per-file-ignores = {"tests/*" = ["S101", "D"]}

[tool.ruff.lint.pydocstyle]
# Options: "google", "numpy", or "pep257"
convention = "google"

[tool.mypy]
exclude = ["^tests/"]
